record_store/inventory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("album/new/", views.album_new, name='album_new'),
    path("artist/new/", views.artist_new, name='artist_new'),
]

record_store/record_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/inventory'), name='logout'),
]

record_store/inventory/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    stock_level = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

record_store/inventory/forms.py
from django import forms
from inventory.models import Album, Artist

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('title', 'year', 'stock_level', 'artist')
        
class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ('name',)

record_store/inventory/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from inventory.models import Artist, Album
from inventory.forms import AlbumForm, ArtistForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    artists = Artist.objects.all()
    return render(request, "inventory/index.html", locals())

@login_required
def album_new(request):
    if request.method == "POST":
        form = AlbumForm(request.POST)
        if form.is_valid():
            album = form.save(commit=False)
            album.save()
        return redirect('index')
    else:
        form = AlbumForm()
        heading = "Album"
        return render(request, 'inventory/new.html', locals())

@login_required
def artist_new(request):
    if request.method == "POST":
        form = ArtistForm(request.POST)
        if form.is_valid():
            artist = form.save(commit=False)
            artist.save()
        return redirect('index')
    else:
        form = ArtistForm()
        heading = "Artist"
        return render(request, 'inventory/new.html', locals())

record_store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title>Record Store</title>
</head>
<body>
	<div class="header">
			<div>
				<nav class="navbar navbar-expand-lg">
					<ul class="navbar-nav">
						<li class="nav"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
						{% if user.is_authenticated %}
						<li class="nav"><a class="navbar-brand " href="{% url 'album_new' %}" >Add Album</a></li>
						<li class="nav"><a class="navbar-brand " href="{% url 'artist_new' %}" >Add Artist</a></li>
					</div>
					<div >
						<p class="welcome">Hello {{ user.first_name }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
					</div>
					{% else %}
					<li class="nav"><a class="navbar-brand " href="{% url 'login' %}">Log in</a></li>
				</div>
					{% endif %}
				</ul>
			</nav>
		</div>
	</div>
	<div class="page-header">
		<h1><a href="/inventory">Al's Record Emporium</a></h1>
	</div>

	{% block content %}

	{% endblock %}
</body>
</html>

record_store/templates/inventory/index.html
{% extends "base.html" %}

{% block content %}

<div class="content container">
	<div class="row">
		<div class="col-md-8">
			{% for artist in artists %}
			<div class="inventory-item">
			<h2>{{ artist.name }}</h2>
			{% for album in artist.album_set.all %}
				<li>{{ album.title }} - {{ album.year }}</li>

			{% endfor %}
			</div>
			{% endfor %}

		</div>
	</div>
</div>
{% endblock %}

record_store/templates/inventory/new.html
{% extends 'base.html' %}

{% block content %}
    <h2>New {{heading}}</h2>
    <form method="POST" class="inventory-form">
      {% csrf_token %}
      <div class="form-group">
        {{ form.as_p }}
        </div>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}